[project]
name = "mlflow_tutorial"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.89.0",
    "mlflow[genai]>=3.14.0",
    "numpy>=2.5.0",
    "optuna>=4.8.0",
    "pandas>=2.3.3",
    "requests>=2.33.1",
    "scikit-learn>=1.9.0",
    "skops>=0.14.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]
